init:
	go mod tidy
run_publisher:
	go run publisher/publisher.go
run_subscriber_info:
	go run subscriber/subscriber.go info
run_subscriber_error_and_fatal:
	go run subscriber/subscriber.go error fatal